export { default as Login } from "./login/Login";
export { default as Register } from "./register/Register";
export { default as Home } from "./home/Home";
export { default as OTP } from "./otp/OTP";
export { default as Order } from "./order/Order";
export { default as Campaigns } from "./campaigns/Campaigns";
export { default as Cart } from "./cart/Cart";
export { default as CartSummary } from "./cart/CartSummary"
export { default as Review } from "./review/Review"
export { default as Favorites } from "./favorites/Favorites"
export { default as Profile } from "./profile/Profile"
export { default as EditProfile } from "./profile/EditProfile"
export { default as AddAddress } from "./address/AddAddress"

export { default as OrderDetails } from "./order/OrderDetails"
export { default as CancelRequest } from "./order/CancelRequest"
export { default as RaiseIssue } from "./order/RaiseIssue"
export { default as DeliveryAddress } from "./order/DeliveryAddress"
export { default as Apperments } from "./apperments/Apperments"
export { default as PaymentMethod } from "./payment/PaymentMethod"